module.exports = {
  renderDiagnostica, pluginAttivi,
  renderEntityPanel, renderSessionPanel, renderBacklinks,
  renderAxesCompare, radarSvg, clampAxis,
  renderProfilo, archetipiMatch, profiloTags, matchesCond,
  renderCoerenza, confrontoAssi, coerenzaNote,
  renderClock, clockSvg,
  renderEncounter, xpForCreature,
  renderVerificaGS, verificaGS, gsDifensivo, gsOffensivo, parseStatblockStats,
  renderProgressione,
  renderFiloAvventura,
  renderTabella,
  renderRisorsePG, barPct, barRow,
  renderSpecieTratti, sezioniMarkdown,
  renderIncantesimi,
  renderTimeline, renderTimelineCorsie, quandoNum, epocaLabel,
  renderTappe, parseTappa,
  renderTipoProfilo,
  renderCausalita,
  renderMap, renderWorldMap, renderDintorni, renderViaggio, parseCoord,
  renderPressioni, cosmicPush, spinteFronte, renderStatoMondo,
  renderProiezione, forecastHeat, renderTensioni, renderMemoria,
  renderCondizioni, condizioniMarkdown,
  renderMaestrie, maestrieMarkdown,
  renderAttacchi, attaccoArma, abilitaArma, danniArma, nomeArma, armiHomebrew,
  renderAlbero, parseNodo,
  radarMarkdownFromValues,
  renderTemaNatale, temaNataleMarkdown,
  renderConnessioni,
};
